language: ruby
before_script:
  - mysql -e 'create database rla_test;'
  - psql -c 'create database rla_test;' -U postgres
script: bundle exec rake
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
gemfile:
  - Gemfile.activerecord2
  - Gemfile.activerecord3
  - Gemfile.activerecord4
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
  exclude:
    - gemfile: Gemfile.activerecord4
      rvm: 1.8.7
    - gemfile: Gemfile.activerecord4
      rvm: ree
    - gemfile: Gemfile.activerecord4
      rvm: jruby-18mode
    - gemfile: Gemfile.activerecord4
      rvm: rbx-18mode
notifications:
  email:
    - info@railsdoctors.com
